### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by irajneeshgupta** [algolia-samples/algoliasearch-magento-2-pwa#4]
Can anyone please guide why this jsx not parsing while build?

ERROR in ./@algolia/src/override/AlgoliaAutocomplete/autocomplete.js 24:4
    Module parse failed: Unexpected token (24:4)
    **You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders**
    `| |   return (
    >     <div className={rootClassName} data-cy="SearchBar-root" ref={ref}>
    |       <div className="app-container">
    |         <AlgoliaAutocomplete` 
   
     @ ./@algolia/src/override/AlgoliaAutocomplete/index.js 1:0-41 1:0-41

**Comment by irajneeshgupta** [comment]
@mohitalgolia can you please let me know ?

Thanks

**Comment by irajneeshgupta** [comment]
update ,
 "@magento/pwa-buildpack": "~11.4.0", for this buildpack it worked fine.Mine was **~11.4.1** in which it failed.

**Comment by irajneeshgupta** [comment]
I am able to make this up ..
Is there any demo link available for project ?

**Comment by mohitalgolia** [comment]
@irajneeshgupta , We don't have any live demos. Thanks

**Comment by rachel-trott** [comment]
Closing this.
